### ISSUE TITLE
Resource interpreted as Image but transferred with MIME type text/html

### ISSUE THREAD

**Issue by rhetskylar** [ajbrown/angular-loggly-logger#18]
`Resource interpreted as Image but transferred with MIME type text/html`received for every request made to loggly. Actual text is `{"response" : "ok"}` with all functionality working and loggly receiving all requests. Trying to understand best method to remove the client-side warning. Thoughts?

**Comment by Bochenski** [comment]
I'm also seeing this.  Seems related to this: https://github.com/loggly/loggly-jslogger/issues/3#issuecomment-54332474.  So we'd need to follow this advice: "you can send tags as a separate field as part of the data"

**Comment by psquickitjayant** [comment]
@rhetskylar this is fixed in the latest update
