### ISSUE TITLE
$log.log undefined throws error

### ISSUE THREAD

**Issue by davidcai** [ajbrown/angular-loggly-logger#19]
I would expect the following code to log "undefined" in console:

var a;
$log.log(a);

However, I got "TypeError: Cannot read property 'stack' of undefined" error. And because of this error, some JS code couldn't complete running, which caused an error state in my app.

Line 207: if(angular.isDefined(msg.stack)){ ... might also need to check if msg is undefined?

Thanks.

**Comment by ajbrown** [comment]
THanks @davidcai. I'll push an update for this shortly.
