### ISSUE TITLE
Rename module to not use the ng prefix

### ISSUE THREAD

**Issue by amitaibu** [ajbrown/angular-loggly-logger#2]
I believe the ``ng`` prefix (as in ``ngLoggly``) as meant to be used only for Angular _core_ modules. Maybe worth changing it?

**Comment by ajbrown** [comment]
I agree

**Comment by ajbrown** [comment]
I'm going to schedule this for a 1.0 release just to make sure it doesn't break anyone implementing this via Bower with fuzzy versioning.

**Comment by ajbrown** [comment]
The new name in 0.1 will be `logglyLogger`

**Comment by amitaibu** [comment]
Thanks :)
