### ISSUE TITLE
Send uncaught errors

### ISSUE THREAD

**Issue by josx** [ajbrown/angular-loggly-logger#20]
Is there any way to send to loggly uncaught errors?
ideas? any clue to solve it?

**Comment by ajbrown** [comment]
Hi @josx.  This is something I'm not actually sure about.  Let me dig into it, and I'll ping back later.

**Comment by josx** [comment]
:+1:  @ajbrown thanks a lot, waiting for your reply

**Comment by mostlyjason** [comment]
There is a config option here:

    // Send console error stack traces to Loggly.  Default is false.
    .sendConsoleErrors( true )

**Comment by josx** [comment]
Added to my conf, but i dont get all unhandled errors.
Is there another way to catch unhandled errors that window.error which is used?

**Comment by boneskull** [comment]
@josx I ended up using [jslogger](/loggly/jslogger) then [decorating the `$log` service](https://gist.github.com/boneskull/e0dcbade0c6dc2d4740f).

**Comment by psquickitjayant** [comment]
@josx  try the following code

```
angular.module( 'ExampleApp', ['logglyLogger'] )
.config( function( LogglyLoggerProvider ) {
	LogglyLoggerProvider.inputToken( 'loggly-token' ).sendConsoleErrors(true);
});
```
