### ISSUE TITLE
Npm install fails unless bower is already installed

### ISSUE THREAD

**Issue by SamPlacette** [ajbrown/angular-loggly-logger#39]
This broke our build the other night. I can reproduce fairly easily.

First, make sure bower is **not** installed locally or globally.

This fails (see attached debug log):
```
mkdir loggly_test
cd loggly_test
npm init --yes
npm install angular-loggly-logger
```

It works if I do it like this:

```
mkdir loggly_test
cd loggly_test
npm init --yes
npm install bower
npm install angular-loggly-logger
```

I believe the fix is simply moving bower into the "dependencies" property of package.json, so it is marked as required for installation. I want to open this issue before working on a fix.

[npm-debug.log.txt](https://github.com/ajbrown/angular-loggly-logger/files/138743/npm-debug.log.txt)

**Comment by ajbrown** [comment]
@SamPlacette To fix this, I went ahead and removed bower as a dependency altogether.  It was only needed for the demo app and to get the angular dependency.  The angular dependency is now pulled in via package.json, and that version is referenced in the demo app.

I'll cut a release for this shortly.
