### ISSUE TITLE
RequireJS Only?

### ISSUE THREAD

**Issue by esetnik** [ajbrown/angular-loggly-logger#40]
The provided installation instructions don't include an alternative for those who don't have `require`.
To get this plugin to work I had to tweak my `bower.json` overrides to include:
```
    "angular-loggly-logger": {
      "main": [
        "angular-loggly-logger.js"
      ]
    }
```
to get main-bower-files to inject the right file. Then I specified the module dependency like:
```
angular
	.module('xxx', [
		'logglyLogger.logger'
	]);
```
and now it works. Maybe this can serve as some helpful documentation for those looking to install as a bower dependency using gulp.

**Comment by ajbrown** [comment]
bower.json now specifies `angular-loggly-logger.js` as the main file instead of `index.js`.

NPM will continue to use `index.js`
