### ISSUE TITLE
stack isn't sent for errors caught by window.onerror

### ISSUE THREAD

**Issue by jaketodaro** [ajbrown/angular-loggly-logger#50]
The stack is only sent for errors caught by the $log provider (I think). Errors caught by `window.onerror` don't sent their stack. I think [this code](https://github.com/ajbrown/angular-loggly-logger/blob/master/angular-loggly-logger.js#L243) needs to change to log the stack from the error object.

```
window.onerror = function (msg, url, line, col, error) {
    logger.sendMessage({
        level : 'ERROR',
        message: msg,
        url: url,
        line: line,
        col: col,
        stack: error && error.stack
    });
...
```

Happy to send a PR.

**Comment by ajbrown** [comment]
@jaketodaro Thanks for pointing this out.  If you want to do a PR, go ahead.  We'll need to make sure this is covered in the unit tests if possible.

**Comment by ajbrown** [comment]
PR: #54
