### ISSUE TITLE
`angular-mocks` and `angular-loader` should be `devDependencies`

### ISSUE THREAD

**Issue by jaketodaro** [ajbrown/angular-loggly-logger#56]
These libs are not dependencies, they are dev dependencies. This is causing bower install conflicts in my app. https://github.com/ajbrown/angular-loggly-logger/blob/master/bower.json#L28

Also, `0.2.4` should probably be `0.3.0` if you're strictly following semver since new features were added.

I've added a custom bower resolution in my app for now but that isn't ideal.

**Comment by ajbrown** [comment]
@jaketodaro Good callout on semver.  I'll get the deps fixed as well.

**Comment by ajbrown** [comment]
For semver, I'm going to keep this on the 0.2 track for now since it's already published, but in the future we'll correctly bump the minor version when new features are added.

**Comment by ajbrown** [comment]
Fixed
